# .github/workflows/python-ci.yml

name: Python CI

# Add permissions for the workflow to write PR comments
permissions:
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest and generate coverage report
        run: |
          # Run tests and create both a console report and an XML report for the next step
          pytest --cov --cov-report=xml

      # ⬇️ ADD THIS NEW STEP HERE ⬇️
      - name: Post Coverage Comment on PR
        # This step only runs for pull request events
        if: github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          # Tell the action where to find the coverage report
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}